
﻿"use strict";define(['jquery','knockout','templatePath/scripts/config','templatePath/scripts/PersonaBarDialog'],function($,ko,cf,PersonaBarDialog){var helper,bindViewModel,rootFolder,utility,appId;var foldersLoaded=function(conn,data){var foldersData=[];for(var i=0;i<data.length;i++){foldersData.push(data[i]);}
conn.loadingFolders(false);conn.foldersData(foldersData);if(typeof conn.parentFolder()=="undefined"||conn.parentFolder()==""){conn.parentFolder("/");conn.connected(false);}};var folderLoadFailed=function(conn,xhr){conn.loadingFolders(false);var message=xhr.responseJSON.Message;if(message.indexOf('{')==0){message=JSON.parse(message)['error'];}
utility.notifyError(message);};var loadFoldersData=function(conn){if(conn.loadingFolders()){return;}
conn.loadingFolders(true);utility.sf.moduleRoot='dnncorp/DropboxConnector';utility.sf.controller='Services';utility.sf.get('GetAllFolders?id='+conn.id,{},foldersLoaded.bind(this,conn),folderLoadFailed.bind(this,conn));}
var init=function(koObject,connectionHelper,pluginFolder,util){helper=connectionHelper;bindViewModel=koObject;rootFolder=pluginFolder;utility=util;koObject.parentFolder=ko.observable('');koObject.authenticated=ko.observable(false);koObject.loadingFolders=ko.observable(false);koObject.foldersData=ko.observable([]);if(typeof koObject.inEdit==="function"&&typeof koObject.inEdit.subscribe==="function"){koObject.inEdit.subscribe(function(data){if(data===true&&koObject.foldersData().length===0&&koObject.connected()){loadFoldersData(koObject);}});}
if(typeof koObject.open==="function"&&typeof koObject.open.subscribe==="function"){koObject.open.subscribe(function(data){if(data===true&&koObject.foldersData().length===0&&koObject.connected()){loadFoldersData(koObject);}});}
if(typeof dnn==='undefined'){window.Sys=!window.Sys?window.top.Sys:window.Sys;window.dnn=!window.dnn?window.top.dnn:window.dnn;window.String=!window.String?window.top.String:window.String;window.String.format=!window.String.format?window.top.String.format:window.String.format;}
processData(koObject);};var onSave=function(conn){if(typeof conn.parentFolder!=="undefined"){conn.configurations.push({name:'ParentFolder',value:ko.protectedObservable(conn.parentFolder())});}}
var processData=function(conn,id,callback){conn.id=id||conn.id;for(var i=conn.configurations.length-1;i>=0;i--){var config=conn.configurations[i];if(config.name!='AppId'&&config.name!='AppSecret'){switch(config.name.toLowerCase()){case'connected':conn.connected(config.value()=='true');conn.configurations.splice(i,1);break;case'authpage':conn.authPage=config.value();break;case"parentfolder":conn.parentFolder(conn.parentFolder()||config.value());conn.configurations.splice(i,1);break;}}else if(config.name=='AppId'){appId=config.value();}else if(config.name=='AppSecret'){conn.appSecret=config.value();}else if(config.name=='Id'){id=conn.id;}}
conn.connected(!(typeof conn.parentFolder()=="undefined"||conn.parentFolder()==""));if(typeof callback==="function"){callback();}}
var getCookie=function(name,success,fail,conn){utility.sf.moduleRoot='dnncorp/DropboxConnector';utility.sf.controller='Services';utility.sf.call('GET','GetAuthCookie?id='+conn.id,{},function(data){if(data.value){success(data.value,conn);}else{fail();}},function(xhr){},null,null,false,true);}
var removeCookie=function(name,conn){utility.sf.moduleRoot='dnncorp/DropboxConnector';utility.sf.controller='Services';utility.sf.call('GET','RemoveAuthCookie?id='+conn.id,{},function(data){},function(xhr){},null,null,true,true);}
var onSaveComplete=function(conn,id){processData(conn,id,function(){conn.previousConnectionState(conn.connected());});if(!conn.connected()&&appId!=''&&conn.appSecret!=''){showAuthWindow(conn);}else{utility.notify((utility.resx.Connectors||utility.resx.PersonaBar).txt_Saved,true);}}
var checkCookieTimer;var cookieTimeout=500;var showAuthWindow=function(conn){var url=conn.authPage.replace('{0}',conn.id);popupwindow(url,'DropboxAuth',770,600);if(checkCookieTimer){clearTimeout(checkCookieTimer);}
checkCookieTimer=setTimeout(checkCookieForAuth.bind(this,conn),cookieTimeout);}
var checkCookieForAuth=function(conn){var dropboxAuthCookieName='DropboxAuthCookie_'+conn.id;getCookie(dropboxAuthCookieName,function(authCookie,conn){removeCookie(dropboxAuthCookieName,conn);var funcName=authCookie.split("(")[0];var success=eval(authCookie.split("(")[1].split(",")[0]);var message=authCookie.split("'")[1].split("'")[0];window[funcName](success,message,conn);},function(){checkCookieTimer=setTimeout(checkCookieForAuth.bind(this,conn),cookieTimeout);},conn);}
var popupwindow=function(url,title,width,height){var winLeft=window.screenLeft?window.screenLeft:window.screenX;var winTop=window.screenTop?window.screenTop:window.screenY;var left=winLeft+(window.innerWidth-width)/2;var top=winTop+(window.innerHeight-height)/2;var params='toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=no, resizable=no, copyhistory=no,'+'width='+width+', height='+height+', top='+top+', left='+left;return window.open(url,title,params);}
var authCallback=window["DropboxAuthCallback"]=function(success,message,conn){if(message.indexOf('{')==0){message=JSON.parse(message)['error'];}
$('.personaBarDialog .actions .btn-cancel').click();if(!success){conn.authenticated(false);utility.notifyError(message);}else{utility.notify(bindViewModel.resx.AuthenticationSuccess,true);conn.authenticated(true);var c={name:'connected',value:ko.protectedObservable('true')};conn.configurations.push(c);loadFoldersData(conn);processData(conn);}}
var authenticate=function(conn,e){e.preventDefault();$.each(conn.configurations,function(i,v){v.value.commit();});saveConnection(conn,onSaveComplete.bind(this,conn));}
var onSaveConnection=false;var saveConnection=function(conn,success){if(onSaveConnection)return;onSaveConnection=true;if(conn.connector()){conn.connector().onSave(conn);}
utility.sf.moduleRoot='personaBar';utility.sf.controller='Connectors';var postData={name:conn.name,displayName:conn.displayName(),id:conn.id,configurations:[]};for(var i=0;i<conn.configurations.length;i++){var c=conn.configurations[i];var value=c.value();postData.configurations.push({name:c.name,value:c.value()});}
if(!postData.configurations[0].value&&!postData.configurations[1].value){return conn.onDelete(conn);}
utility.sf.call('POST','SaveConnection',postData,function(d){if(d&&d.Success){success(d.Id);}else{var message=d.Message;utility.notifyError(message||'Failed...');}
onSaveConnection=false;},function(){var message=d.Message;utility.notifyError(message||'Failed...');onSaveConnection=false;},null,null,true,false);};var getActionButtons=function(){return[{className:'primarybtn',text:bindViewModel.resx.Save,action:function(conn,e){if(!conn.connected()){authenticate(conn,e);}else{conn.save(conn,e,onSaveComplete.bind(this,conn,conn.id));}}}];}
return{init:init,onSave:onSave,getActionButtons:getActionButtons}});