const actionTypes = {
    RETRIEVED_ENABLED_STATUS: "ANALYTICS_RETRIEVED_ENABLED_STATUS",
    UPDATE_ENABLED_STATUS: "ANALYTICS_UPDATE_ENABLED_STATUS",
    SAVED_ENABLED_STATUS: "ANALYTICS_SAVED_ENABLED_STATUS"
};
export default actionTypes;
