
﻿"use strict";define(["jquery","knockout","templatePath/scripts/config","templatePath/scripts/PersonaBarDialog"],function($,ko){var helper,bindViewModel,rootFolder,utility,appId,appSecret,bucket;var init=function(koObject,connectionHelper,pluginFolder,util){helper=connectionHelper;bindViewModel=koObject;rootFolder=pluginFolder;utility=util;koObject.bucket=ko.observable("");koObject.loadingFolders=ko.observable(false);koObject.foldersData=ko.observable([]);if(typeof dnn==="undefined"){window.Sys=!window.Sys?window.top.Sys:window.Sys;window.dnn=!window.dnn?window.top.dnn:window.dnn;window.String=!window.String?window.top.String:window.String;window.String.format=!window.String.format?window.top.String.format:window.String.format;}
processData(koObject);}
var fieldsHaveValues=function(conn){return conn.configurations[0].value()!=""&&conn.configurations[1].value()!="";}
var onSave=function(conn){if(typeof conn.bucket!=="undefined"){conn.configurations.push({name:"Bucket",value:ko.protectedObservable(conn.bucket())});}}
var processData=function(conn,id){conn.id=id||conn.id;for(var i=conn.configurations.length-1;i>=0;i--){var config=conn.configurations[i];if(config.name!="AccessKeyId"&&config.name!="SecretAccessKey"&&config.name!="Id"){switch(config.name.toLowerCase()){case"connected":conn.connected(config.value()=="true");conn.configurations.splice(i,1);break;case"bucket":conn.bucket(conn.bucket()||config.value());conn.configurations.splice(i,1);break;}}else if(config.name=="AccessKeyId"){appId=config.value();}else if(config.name=="SecretAccessKey"){appSecret=config.value();}else if(config.name=="Id"){id=config.value();}}
conn.connected(!(typeof conn.bucket()=="undefined"||conn.bucket()==""));if(conn.id&&conn.foldersData().length===0)
loadFoldersData(conn);}
var loadFoldersData=function(conn){conn.loadingFolders(true);utility.sf.moduleRoot="dnncorp/AmazonS3Connector";utility.sf.controller="Services";utility.sf.get("GetAllBuckets?id="+conn.id,{},foldersLoaded.bind(this,conn),folderLoadFailed.bind(this,conn));};var foldersLoaded=function(conn,data){conn.loadingFolders(false);var foldersData=[conn.resx.SelectFolder];for(var i=0;i<data.length;i++){foldersData.push(data[i]);}
conn.foldersData(foldersData);if(typeof conn.bucket()=="undefined"||conn.bucket()==""){conn.bucket("/");}};var folderLoadFailed=function(conn,xhr){conn.loadingFolders(false);var message=xhr.responseJSON.Message;if(message.indexOf("{")==0){message=JSON.parse(message)["error"];}
utility.notifyError(message);};var onSaveComplete=function(conn,id){if(!fieldsHaveValues(conn)){conn.foldersData.removeAll();return;}
processData(conn,id);utility.notify((utility.resx.Connectors||utility.resx.PersonaBar).txt_Saved,true);}
var authenticate=function(conn,e){e.preventDefault();$.each(conn.configurations,function(i,v){v.value.commit();});saveConnection(conn,onSaveComplete.bind(this,conn));}
var onSaveConnection=false;var saveConnection=function(conn,success){if(onSaveConnection)return;onSaveConnection=true;if(conn.connector()){conn.connector().onSave(conn);}
utility.sf.moduleRoot="personaBar";utility.sf.controller="Connectors";var postData={name:conn.name,configurations:[],id:conn.id,displayName:conn.displayName()};for(var i=0;i<conn.configurations.length;i++){var c=conn.configurations[i];var value=c.value();postData.configurations.push({name:c.name,value:c.value()});}
if(!postData.configurations[0].value&&!postData.configurations[1].value){return conn.onDelete(conn);}
utility.sf.call("POST","SaveConnection",postData,function(d){if(d&&d.Success){success(d.Id);}else{var message=d.responseJSON.Message;utility.notifyError(message||"Failed...");}
onSaveConnection=false;},function(d){var message=d.responseJSON.Message;utility.notifyError(message||"Failed...");onSaveConnection=false;},null,null,true,false);};var getActionButtons=function(){return[{className:"primarybtn",text:"Save",action:function(conn,e){conn.save(conn,e,onSaveComplete.bind(this,conn,conn.id));}}];};return{init:init,onSave:onSave,getActionButtons:getActionButtons}});