
﻿
window.dnn=dnn||{};window.dnn.personalizedTabs=dnn.personalizedTabs||{};window.dnn.personalizedTabs.rules=dnn.personalizedTabs.rules||{};(function IIFE(){var ReferrerRuleClass;ReferrerRuleClass=(function IIFE(){'use strict';var HTML_PATH="Assests/Html/Rules/ReferrerRuleTemplate.html";var URL_REGEX=/^(https?):\/\/(((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:)*@)?(((\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5]))|((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)*(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?)(:\d*)?)(\/((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)+(\/(([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)*)*)?)?(\?((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|[\uE000-\uF8FF]|\/|\?)*)?(#((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|\/|\?)*)?$/i;var URL_VALID_CHARS_REGEX=/^[a-zA-Z0-9\-\._\~\:\/\?\#\[\]\@\!\$\&\'\(\)\*\+\,\;\=]*$/;var _templateLoader,_resx;var getViewModel,remove,prependHttpIfNeeded,validateExactMatch;ReferrerRule.class='ReferrerRule';ReferrerRule.type='Class';ReferrerRule.template;ReferrerRule.allowMultipleInstances=false;function ReferrerRule(onDeleteRuleCallback,resx){_resx=resx;this._id="";this._viewModel={};this._ruleElement=null;this.onDeleteRuleCallback=onDeleteRuleCallback;_templateLoader=window.dnn.personalizedTabs.TemplateLoader;if(!ReferrerRule.template){_templateLoader.readHtmlTemplate(dnn.getVar('dnn_content_personalization_resourceroot')+HTML_PATH,function(template){ReferrerRule.template=template;});}}
prependHttpIfNeeded=function(value){var regex=/^(https?):\/\//;return regex.test(value)?value:"http://"+value;}
validateExactMatch=function(matchingText){var url=prependHttpIfNeeded(matchingText);if(!URL_REGEX.test(url)){return false;}
var host=url.split("/")[2];return host.split(".").length>1;}
getViewModel=function(self,data){self._viewModel={id:self._id,remove:remove,self:self,resx:_resx,exactMatch:ko.observable("exactMatch"),matchingText:ko.observable("").trimmed().extend({required:true,validation:{validator:function(value){if(self._viewModel.exactMatch()==="exactMatch"){this.message=_resx.RulesReferrerValidationErrorExactMatch;return validateExactMatch(value);}else{this.message=_resx.RulesReferrerValidationErrorContains;return URL_VALID_CHARS_REGEX.test(value);}}}})};self._viewModel.matchingTextPlaceholder=ko.computed(function(){return self._viewModel.exactMatch()==="exactMatch"?_resx.RulesReferrerPlaceholderExactMatch:_resx.RulesReferrerPlaceholderContains;});if(data){var exactMatch=data.ExactMatch?"exactMatch":"contains";self._viewModel.exactMatch(exactMatch);self._viewModel.matchingText(data.MatchingText);};self._viewModel.validationObservable=ko.validatedObservable({matchingText:self._viewModel.matchingText});};remove=function(){if(this.self.onDeleteRuleCallback&&typeof this.self.onDeleteRuleCallback==='function'){this.self.onDeleteRuleCallback(this.id);}};ReferrerRule.getId=function(){return"ReferrerRule";};ReferrerRule.getName=function(resx){return resx.RulesReferrerName;};ReferrerRule.loadTemplate=function(callback){if(!ReferrerRule.template){_templateLoader.readHtmlTemplate(dnn.getVar('dnn_content_personalization_resourceroot')+HTML_PATH,function(template){ReferrerRule.template=template;callback();});}else{callback();}}
ReferrerRule.prototype.getId=function(){return this._id;};ReferrerRule.prototype.injectRule=function(parentElement,afterInjectCallback,data){var self=this;ReferrerRule.loadTemplate(function(){var dateNow=new Date().getTime();var html=ReferrerRule.template.replace(/\{0\}/g,dateNow);parentElement.append(html);self._id=dateNow;self._ruleElement=$("#{0}".replace(/\{0\}/g,self._id));getViewModel(self,data);ko.applyBindings(self._viewModel,self._ruleElement[0],{decorateElement:true,insertMessages:true,deep:true});afterInjectCallback(self,parentElement,self._viewModel.validationObservable);});}
ReferrerRule.prototype.getDataToBeSent=function(){if(!this._viewModel){return;}
var exactMatch=this._viewModel.exactMatch()==="exactMatch";return{type:"ReferrerRule",exactMatch:exactMatch,matchingText:exactMatch?prependHttpIfNeeded(this._viewModel.matchingText()):this._viewModel.matchingText()};}
ReferrerRule.prototype.freeContext=function(){var element=$("#{0}".replace(/\{0\}/g,this._id));ko.cleanNode(element);}
ReferrerRule.prototype.doesRuleAllowMultipleInstances=function(){return ReferrerRule.allowMultipleInstances;};ReferrerRule.prototype.getRuleClass=function(){return ReferrerRule.class;};return ReferrerRule;})();window.dnn.personalizedTabs.rules.ReferrerRule=ReferrerRuleClass;}).call(this);