"use strict";define(['jquery','knockout','templatePath/scripts/PersonaBarDialog'],function($,ko,PersonaBarDialog){var init=function(bindViewModel,helper,rootFolder,utility){var ProfileModel,WebPropertyModel,AccountModel,integrationViewModel,getToken,getIntegrationViewModel,onIntegrationClick,onIntegrationSettingAccept,onIntegrationSettingCancel,onAfterBind,setProfile,getProfile,onAuthMessage,popupWindow,onAuthorize,onUnAuthorize,validateToken,refreshAccounts,localStorageAllowed,loadLocalizedStrings,callSaveAction,checkAuthorizeStatus,accessToken,gaServiceUrl='',addEvent;ProfileModel=function(m,webPropertyId){if(m){return{webPropertyId:webPropertyId,profileId:ko.observable(m.ProfileId),name:ko.observable(m.Name),timezoneName:ko.observable(m.TimezoneName),accountId:ko.observable(m.AccountId),timezone:ko.observable(m.Timezone)}}}
WebPropertyModel=function(m,accountId){if(m){var profiles=[];m.Profiles.forEach(function(item){profiles.push(new ProfileModel(item,m.WebPropertyId));});return{accountId:accountId,name:ko.observable(m.Name),webPropertyId:ko.observable(m.WebPropertyId),description:ko.observable('['+m.WebPropertyId+'] '+m.Name),webSiteUrl:ko.observable(m.WebSiteUrl),hostName:ko.observable(m.HostName),profiles:ko.observableArray(profiles)}}};AccountModel=function(m){if(m){var properties=[];m.WebProperties.forEach(function(item){properties.push(new WebPropertyModel(item,m.AccountId));});return{accountId:ko.observable(m.AccountId),name:ko.observable(m.Name),webProperties:ko.observableArray(properties)}}};onAfterBind=function(){}
callSaveAction=function(){$("#connector-GoogleAnalytics .edit-items.edit-buttons .primarybtn").click();}
getIntegrationViewModel=function(){if(!integrationViewModel){integrationViewModel={resx:bindViewModel.resx,account:ko.observable(''),webProperty:ko.observable(''),profile:ko.observable(''),accountsData:ko.observableArray([]),webPropertiesData:ko.observableArray([]),profilesData:ko.observableArray([]),loadingAccounts:ko.observable(false),loadingWebProperties:ko.observable(false),loadingProfiles:ko.observable(false)}
integrationViewModel.disableSave=ko.computed(function(){var loading=integrationViewModel.loadingAccounts()||integrationViewModel.loadingWebProperties()||integrationViewModel.loadingProfiles()||!integrationViewModel.account()||!integrationViewModel.webProperty()||!integrationViewModel.profile();return loading;});integrationViewModel.disableDisconnect=ko.computed(function(){var loading=integrationViewModel.loadingAccounts()||integrationViewModel.loadingWebProperties()||integrationViewModel.loadingProfiles();return loading;});integrationViewModel.account.subscribe(function(){var account=ko.utils.arrayFilter(integrationViewModel.accountsData(),function(item){return item.accountId()===integrationViewModel.account();});if(account.length>0){integrationViewModel.webPropertiesData(account[0].webProperties());}else{integrationViewModel.webPropertiesData(null);}
integrationViewModel.webProperty(undefined);integrationViewModel.profile(undefined);},integrationViewModel);integrationViewModel.webProperty.subscribe(function(){bindViewModel.setTrackingId(bindViewModel.integration.webProperty());var webProperty=ko.utils.arrayFilter(bindViewModel.integration.webPropertiesData(),function(item){return item.webPropertyId()===bindViewModel.integration.webProperty();});if(webProperty.length>0){bindViewModel.integration.profilesData(webProperty[0].profiles());}else{bindViewModel.integration.profilesData(null);}
bindViewModel.integration.profile(undefined);},bindViewModel);}
return integrationViewModel;}
popupWindow=function(url,title,w,h){var left=(screen.width/2)-(w/2);var top=(screen.height/2)-(h/2);return window.open(url,title,'toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=no, resizable=no, copyhistory=no, width='+w+', height='+h+', top='+top+', left='+left);};onAuthorize=function(){var myWindow=popupWindow('about:blank','GoogleAuth',1090,600);var url=utility.sf.getSiteRoot()+"DesktopModules/dnncorp/ContentGoogleAnalyticsConnector/API/Services/GetAuthUri";myWindow.location=url;return false;};var setTrackingId=function(value){for(var i=0;i<bindViewModel.configurations.length;i++){var config=bindViewModel.configurations[i];if(config.name==="TrackingId"){config.value(value);break;}}}
onUnAuthorize=function(){var resx=bindViewModel.resx;utility.confirm(resx.UnlinkConfirm,resx.Disconnect,resx.Cancel,function(){utility.sf.moduleRoot='dnncorp/ContentGoogleAnalyticsConnector';utility.sf.controller='Services';utility.sf.get('GetToken',{},function(data){accessToken=data.AccessToken;gaServiceUrl=data.ServiceUrl;if(!validateToken())
return;$.ajax({method:"GET",dataType:"json",url:gaServiceUrl+"api/googleanalytics/deauthorize",beforeSend:function(xhr){xhr.setRequestHeader("Authorization","Bearer "+accessToken);},success:function(m){utility.sf.moduleRoot='dnncorp/ContentGoogleAnalyticsConnector';utility.sf.controller='Services';utility.sf.get('Deauthorize',{},function(data){bindViewModel.setTrackingId("");bindViewModel.authorized(false);callSaveAction();});},error:function(e){console.error(e.responseText);utility.notifyError(e.responseText);}});});});return false;}
var onCancel=function(){$("#connector-GoogleAnalytics .edit-items.edit-buttons .secondarybtn").click();}
var onSave=function(){if(integrationViewModel.account()===undefined||integrationViewModel.webProperty()===undefined||integrationViewModel.profile()===undefined){window.event.preventDefault();return;}
setProfile(function(){callSaveAction();});}
validateToken=function(){if(accessToken===''||gaServiceUrl===''){var msg='There is no valid token or the service URL was not found';console.error(msg);utility.notifyError(msg);return false;}
return true;};refreshAccounts=function(){if(!validateToken())
return;integrationViewModel.loadingAccounts(true);$.ajax({method:"GET",dataType:"json",url:gaServiceUrl+"api/googleanalytics/accounts",beforeSend:function(xhr){xhr.setRequestHeader("Authorization","Bearer "+accessToken);},success:function(items){integrationViewModel.loadingAccounts(false);integrationViewModel.accountsData.removeAll();items.Accounts.forEach(function(item){integrationViewModel.accountsData.push(new AccountModel(item));});getProfile();},error:function(e){console.error(e.responseText);utility.notifyError(e.responseText);}});};getProfile=function(){if(!validateToken())
return;integrationViewModel.loadingWebProperties(true);$.ajax({method:"GET",dataType:"json",url:gaServiceUrl+"api/googleanalytics/profile",beforeSend:function(xhr){xhr.setRequestHeader("Authorization","Bearer "+accessToken);},success:function(r){integrationViewModel.loadingWebProperties(false);integrationViewModel.account(r.AccountId);integrationViewModel.webProperty(r.WebPropertyId);integrationViewModel.profile(r.ProfileId);},error:function(e){if(e.status===200)return;console.error(e.responseText);utility.notifyError(e.responseText);}});};setProfile=function(afterSetProfile){if(!validateToken())
return;var accountId=encodeURI(integrationViewModel.account());var webPropertyId=encodeURI(integrationViewModel.webProperty());var profileId=encodeURI(integrationViewModel.profile());$.ajax({method:"POST",dataType:"json",url:gaServiceUrl+"api/googleanalytics/profile?accountId="+accountId+"&webPropertyId="+webPropertyId+"&profileId="+profileId,beforeSend:function(xhr){xhr.setRequestHeader("Authorization","Bearer "+accessToken);},success:function(r){if(afterSetProfile)afterSetProfile();},error:function(e){if(e.status===200){if(afterSetProfile)afterSetProfile();return;}
console.error(e.responseText);utility.notifyError(e.responseText);}});};getToken=function(){utility.sf.moduleRoot='dnncorp/ContentGoogleAnalyticsConnector';utility.sf.controller='Services';utility.sf.get('GetToken',{},function(data){accessToken=data.AccessToken;gaServiceUrl=data.ServiceUrl;bindViewModel.checkingAuthorizationStatus(false);if(!validateToken()){bindViewModel.authorized(false);return;}
bindViewModel.authorized(true);refreshAccounts();});};onAuthMessage=function(e){var ev=window.event||e;if(ev.data.startsWith('gaservice|authOK')){gaServiceUrl=ev.data.substring(17);bindViewModel.authorized(true);getToken();}
else{bindViewModel.authorized(false);}};localStorageAllowed=function(){var mod='DNN_localStorageTEST';try{window.localStorage.setItem(mod,mod);window.localStorage.removeItem(mod);return true;}catch(e){return false;}};loadLocalizedStrings=function(cb){var name="ContentGaConnector";var culture=window.top["personaBarSettings"]["culture"];var config={culture:'en-US'};var allowLocalStorage=localStorageAllowed();var storageName='Connections.'+name+'.'+culture+'.Table';if(allowLocalStorage){if(window.localStorage[storageName]){var table=JSON.parse(window.localStorage[storageName]);var time=new Date().getTime()-table.timestamp;if(time>60*60*1000){window.localStorage.removeItem(storageName);}else{cb(table);return;}}}
utility.sf.moduleRoot='dnncorp/ContentGoogleAnalyticsConnector';utility.sf.controller='Services';utility.sf.get('GetLocalizedString',{culture:culture},function(data){if(allowLocalStorage){try{data.timestamp=new Date().getTime();window.localStorage[storageName]=JSON.stringify(data);}catch(ex){if(ex.name==="QuotaExceededError"){console.log("Local Storage might be full.");}
console.log(ex);if(window.localStorage[storageName]){window.localStorage.removeItem(storageName);}}}
cb(data);});};checkAuthorizeStatus=function(refreshAccountsOnSuccess){bindViewModel.checkingAuthorizationStatus(true);if($("#connector-GoogleAnalytics.edit-form").css("display")!=="block"){bindViewModel.authorized(false);return;}
utility.sf.moduleRoot='dnncorp/ContentGoogleAnalyticsConnector';utility.sf.controller='Services';utility.sf.get('GetToken',{},function(data){accessToken=data.AccessToken;gaServiceUrl=data.ServiceUrl;if(!validateToken()){bindViewModel.checkingAuthorizationStatus(false);bindViewModel.authorized(false);return;}
$.ajax({method:"GET",dataType:"json",url:gaServiceUrl+"api/googleanalytics/isauthorized",beforeSend:function(xhr){xhr.setRequestHeader("Authorization","Bearer "+accessToken);},success:function(m){bindViewModel.checkingAuthorizationStatus(false);bindViewModel.authorized(m);if(refreshAccountsOnSuccess&&m)
refreshAccounts();},error:function(){bindViewModel.checkingAuthorizationStatus(false);bindViewModel.authorized(false);}});});};addEvent=function(evnt,elem,func){if(elem.addEventListener)
elem.addEventListener(evnt,func,false);else if(elem.attachEvent){elem.attachEvent("on"+evnt,func);}
else{$(elem).on(evnt,func);}};loadLocalizedStrings(function(data){bindViewModel.resx=$.extend({},bindViewModel.resx,data);bindViewModel.authorized=ko.observable(false);bindViewModel.checkingAuthorizationStatus=ko.observable(true);bindViewModel.onAuthorize=onAuthorize;bindViewModel.onUnAuthorize=onUnAuthorize;bindViewModel.onCancel=onCancel;bindViewModel.onSave=onSave;bindViewModel.setTrackingId=setTrackingId;$('#connector-GoogleAnalytics .gaBaseFields').css("display","none");$('#connector-GoogleAnalytics .advancedSetting').css("display","none");bindViewModel.authorized.subscribe(function(newValue){setTimeout(function(){$("#connector-GoogleAnalytics .connectPanel .primarybtn").html(bindViewModel.resx.ConnectToGA);},100);$('#connector-GoogleAnalytics .gaBaseFields').css("display",newValue?"block":"none");$('#connector-GoogleAnalytics .advancedSetting').css("display",newValue?"block":"none");});checkAuthorizeStatus();document.getElementById("gaTrackingId").disabled=true;addEvent('message',window,onAuthMessage);bindViewModel.integration=getIntegrationViewModel();$(".socialnetwork-favicon.GoogleAnalytics").first().parent().parent().find(".primarybtn").on("click",getToken);$(".socialnetwork-favicon.GoogleAnalytics").first().parent().parent().find(".plainbtn").on("click",function(){$("#connector-GoogleAnalytics .connectPanel .primarybtn").html(bindViewModel.resx.ConnectToGA);checkAuthorizeStatus(true);});require(['text!rootPath'+rootFolder+'authroize.htm','css!rootPath'+rootFolder+'authroize.css'],function(authorizeHtml){$('#connector-GoogleAnalytics').find('a.advancedSetting').before(authorizeHtml);$('#connector-GoogleAnalytics').find('.edit-fields').children().each(function(){ko.cleanNode(this);ko.applyBindings(bindViewModel,this);});});});}
return{init:init}});