
if(typeof dnn==="undefined"||dnn===null){dnn={};};(function($){"use strict";var editingModuleId;var containerPaneName;var visualizerDesktopModuleId;var serviceName="structuredcontentvisualizer";function loadParams(){var sf=$.dnnSF();var serviceRoot=sf.getServiceRoot(serviceName);var serviceUrl=serviceRoot+"visualizer/getparams";return $.ajax({url:serviceUrl,type:"GET",beforeSend:sf.setModuleHeaders});}
function hideOverlay(){$("#structuredContentVisualizeriframe").hide();$("body").css("overflow","");}
function closeModal(shouldRefresh){setTimeout(hideOverlay,400);if(!editingModuleId){var moduleDialog=getModuleDialog();moduleDialog.close();moduleDialog.getModuleManager().getHandler().click();}else{if(shouldRefresh){refreshModule();}}}
function setModuleSettings(moduleId,options){var serviceController=new dnn.dnnModuleService({service:serviceName,controller:"Settings",async:false,moduleId:moduleId});function successCallbackHandler(){$(document).trigger("changeOnPageContent");window.dnn.visualizer.notifyAddedModule();hideOverlay();if(editingModuleId){refreshModule();}}
serviceController.request('Set','POST',options,successCallbackHandler);}
function refreshModule(){var moduleDialog=getModuleDialog();moduleDialog.refreshPane("dnn_"+containerPaneName);}
function addModule(options){if(editingModuleId){setModuleSettings(editingModuleId,options);return;}
var moduleDialog=getModuleDialog();moduleDialog.addModule(visualizerDesktopModuleId,function onAddedModule(moduleId){setModuleSettings(moduleId,options);},true);}
function updateModule(options){setModuleSettings(editingModuleId,options);}
function addVisualizerIframe(config){var visualizerId="structuredContentVisualizer";var $visualizerIframe=$("#"+visualizerId+"iframe");var requireScriptUrl=config.scriptBaseUrl+"/require.js";var mainScriptUrl=config.scriptBaseUrl+"/main.js";var loadingImageUrl=config.siteRoot+"Images/loading.gif";if($visualizerIframe.length===0){var iframeContent="<!DOCTYPE html><html><head></head><body>"+"<div style='display: none' id='content-filePickerEvoqParentId'></div>"+"<div id='"+visualizerId+"' data-init-callback='dnnInitVisualizer'>"+"<img src='"+loadingImageUrl+"' style='position: absolute; top: 50%; left: 50%;' />"+"</div>"+"<script type='text/javascript' data-main='"+mainScriptUrl+"' src='"+requireScriptUrl+"'></script>"+"</body></html>";$visualizerIframe=$("<iframe id='"+visualizerId+"iframe'></iframe>");$visualizerIframe.css({"z-index":2000,position:"fixed",width:"100%",height:"100%",top:0,left:0,display:"none"});$(document.body).append($visualizerIframe);var doc=$visualizerIframe[0].contentDocument;doc.open();doc.write(iframeContent);doc.close();var win=$visualizerIframe[0].contentWindow;win.visualizerModuleEditorConfig={editingModuleId:editingModuleId,config:config,addModule:addModule,updateModule:updateModule,closeModal:closeModal}}}
function getModuleListItem(desktopModuleId){var $dialogElement=getModuleDialogElement();var $moduleList=$dialogElement.find('.dnnModuleList ul');return $moduleList.find('.dnnModuleItem[data-moduleid="'+desktopModuleId+'"]');}
function getModuleDialog(){return dnn.ContentEditorManager.getModuleDialog();}
function getModuleDialogElement(){return getModuleDialog().getElement();}
function getLayoutForAdd(){var $dialogElement=getModuleDialogElement();var width=$dialogElement.outerWidth();return{initialWidth:width,initialHeight:$dialogElement.outerHeight(),centerX:$dialogElement.offset().left+width/2}}
function getLayoutForEdit(){var $body=$("body");var personaBarMenuWidth=parseInt($body.css("margin-left"));return{initialWidth:100,initialHeight:100,centerX:personaBarMenuWidth+$("body").width()/2};}
var openVisualizerModalAttempt=0;function openVisualizerModal(permissions,shouldUpdateVisualizerInstance,visualizerInstanceId,mode,detailsPageId){var isEditMode=visualizerInstanceId||mode;if(openVisualizerModalAttempt===0){var overlayColor=isEditMode?"rgba(0,0,0,0.7)":"transparent";$("#structuredContentVisualizeriframe").css("background-color",overlayColor).show();$("body").css("overflow","hidden");}
if(window.dnn.visualizer){var l=isEditMode?getLayoutForEdit():getLayoutForAdd();window.dnn.visualizer.openModal(l.centerX,l.initialWidth,l.initialHeight,visualizerInstanceId,shouldUpdateVisualizerInstance,mode,permissions,detailsPageId);openVisualizerModalAttempt=0;return;}
openVisualizerModalAttempt++;if(openVisualizerModalAttempt===100){openVisualizerModalAttempt=0;hideOverlay();alert("Could not load the visualizer");return;}
setTimeout(function(){openVisualizerModal(permissions,shouldUpdateVisualizerInstance,visualizerInstanceId,mode,detailsPageId);},100);}
function registerAddVisualizerModuleEventHandler(){var $moduleListItem=getModuleListItem(visualizerDesktopModuleId);if($moduleListItem.length!==0){$moduleListItem.click(function onModuleListItemClick(e){editingModuleId=null;containerPaneName=null;updateVisualizerModuleEditorIfNeeded(editingModuleId);e.preventDefault();e.stopImmediatePropagation();var permissions={manageContent:true,editSettings:true};openVisualizerModal(permissions,false);});}}
function registerOnAddModuleCompleteEventHandler(){var $moduleDialog=getModuleDialogElement();$moduleDialog.on('addmodulecomplete',function(e,newModule){dnn.ContentEditorManager.catchSortEvents(function(){newModule.trigger('editmodule');});});}
function initializeVisualizerModuleEditorIfNeeded(callback){if(window.dnn.visualizerModuleEditorInitialized){if(callback)callback();return;}
loadParams().success(function(config){addVisualizerIframe(config);if(callback)callback();});registerOnAddModuleCompleteEventHandler();window.dnn.visualizerModuleEditorInitialized=true;}
function updateVisualizerModuleEditorIfNeeded(id){if(window.dnn.visualizerUpdateConfig){window.dnn.visualizerUpdateConfig({editingModuleId:id});}}
function addModuleEventHandler(desktopModuleId){visualizerDesktopModuleId=desktopModuleId;registerAddVisualizerModuleEventHandler();initializeVisualizerModuleEditorIfNeeded();}
function visualizerModuleEditorLoad(moduleId,shouldUpdateVisualizerInstance,visualizerInstanceId,mode,permissions,detailsPageId,paneName){editingModuleId=moduleId;containerPaneName=paneName;initializeVisualizerModuleEditorIfNeeded(function(){openVisualizerModal(permissions,shouldUpdateVisualizerInstance,visualizerInstanceId,mode,detailsPageId);});updateVisualizerModuleEditorIfNeeded(editingModuleId);}
window.dnn.visualizerModuleEditorLoad=window.dnn.visualizerModuleEditorLoad||visualizerModuleEditorLoad;window.dnn.addVisualizerModuleEventHandler=window.dnn.addVisualizerModuleEventHandler||addModuleEventHandler;return{addModuleHandler:window.dnn.addVisualizerModuleEventHandler};})(jQuery);