'use strict';define(['jquery','./integrations/filePicker','./integrations/imagesService','./integrations/notifier','dnn.servicesframework'],function($,filePicker,imagesService,notifier){var serviceName="structuredcontentvisualizer";function getToken(success,error,forceNewToken){var sf=$.dnnSF();var serviceRoot=sf.getServiceRoot(serviceName);var serviceUrl=serviceRoot+"authorization/GetAuthorizationToken";$.ajax({url:serviceUrl,type:"POST",data:{forceNewToken:forceNewToken},beforeSend:sf.setModuleHeaders}).success(function onSuccess(data){var token=data.token;success(token);}).error(function onError(err){error(err);});}
function getBundleLanguage(culture){var fallbackLanguage="en";var availableLanguages=["en"];return availableLanguages.indexOf(culture)>0?culture:fallbackLanguage;}
function loadScript(config){var publicPath=config.bundlePublicPath;var language=getBundleLanguage(config.culture);var url=publicPath+"bundle-"+language+".js";return $.ajax({dataType:"script",cache:true,url:url});}
function getDetailsPages(contentTypeId,success,error){var sf=$.dnnSF();var serviceRoot=sf.getServiceRoot(serviceName);var serviceUrl=serviceRoot+"visualizer/getdetailpages?contentTypeId="+contentTypeId;$.ajax({url:serviceUrl,type:"GET",beforeSend:sf.setModuleHeaders}).success(function onSuccess(data){success(data);}).error(function onError(err){error(err);});}
function getReferencedVisualizer(success,error){var sf=$.dnnSF();var serviceRoot=sf.getServiceRoot(serviceName);var serviceUrl=serviceRoot+"visualizer/getReferencedVisualizer";$.ajax({url:serviceUrl,type:"GET",beforeSend:sf.setModuleHeaders}).success(function onSuccess(data){success(data);}).error(function onError(err){error(err);});}
function defineInitCallback(moduleConfig){function visualizerInitCallback(){var options={getToken:getToken,tokenKey:moduleConfig.config.tokenKey,addModule:moduleConfig.addModule,updateModule:moduleConfig.updateModule,closeModal:moduleConfig.closeModal,goBackModal:moduleConfig.closeModal,getDetailsPages:getDetailsPages,getReferencedVisualizer:getReferencedVisualizer,publicPath:moduleConfig.config.bundlePublicPath,apiServicePath:moduleConfig.config.apiServicePath,visualizerVersion:moduleConfig.config.visualizerVersion,contentItemChangedListener:notifier.notifyContentItemChange,thumbnailService:moduleConfig.config.siteRoot+"dnnimagehandler.ashx?mode=file&size=xxl&url=",proxyImage:imagesService.proxyImage,saveImage:imagesService.saveImage,filePicker:filePicker}
window.parent.dnn.visualizer=window.dnn.visualizer;window.dnn.visualizer.init(options);}
window.dnnInitVisualizer=visualizerInitCallback;}
function visualizerUpdateConfig(moduleConfig){notifier.init(moduleConfig.editingModuleId);}
var moduleConfig=window.visualizerModuleEditorConfig;notifier.init(moduleConfig.editingModuleId);window.parent.dnn.visualizerUpdateConfig=visualizerUpdateConfig;defineInitCallback(moduleConfig);if(moduleConfig.config.debugMode===true){window.__REACT_DEVTOOLS_GLOBAL_HOOK__=window.parent.__REACT_DEVTOOLS_GLOBAL_HOOK__;window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__=window.parent.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__;}
loadScript(moduleConfig.config);});