"use strict";define(['jquery','knockout','templatePath/scripts/PersonaBarDialog','knockout.validation.min','jquery.mousewheel','dnn.jScrollBar','jquery.tokeninput','css.jScrollBar','css!../../../../Admin/Dnn.PersonaBar/css/tokenInput.css'],function($,ko,PersonaBarDialog){var bindViewModel,advancedViewModel,rootFolder,utility,helper,dnnRolesArray,dnnRolesObject,mailchimpProductsArray,mailchimpProductsObject,$roleTokenInput;var constants={API_KEY:"Mailchimp_ApiKey",INSERT_NEW_USERS_IN_LISTS:'Mailchimp_InsertNewUsersInLists',LISTS_TO_INSERT_NEW_USERS:'Mailchimp_ListsToInsertNewUsers',ROLE_TO_SYNCHRONIZE:'Mailchimp_RoleToSynchronize',PAGE_SIZE:10};var apiKeyChanged=false;var init=function(koObject,connectionHelper,pluginFolder,util){bindViewModel=koObject;rootFolder=pluginFolder;utility=util;helper=connectionHelper;$(document.body).on('click','#connector-Mailchimp .advancedSetting',onAdvancedSettingsClick);initRequiredResources();getAdvancedViewModel();bindViewModel.apiKey=ko.observable(bindViewModel.configurations[0].value()||"");};var initRequiredResources=function(){if(typeof dnn==='undefined'){window.Sys=!window.Sys?window.top.Sys:window.Sys;window.dnn=!window.dnn?window.top.dnn:window.dnn;}
if(typeof window.String==='undefined'||typeof window.String.format==='undefined'){window.String=!window.String?window.top.String:window.String;window.String.format=!window.String.format?window.top.String.format:window.String.format;}}
var onAdvancedSettingsClick=function onAdvancedClick(){require(['text!rootPath'+rootFolder+'advanced.htm'],function(html){var dialog=new PersonaBarDialog({inObject:$('body'),width:771,title:bindViewModel.resx.AdvancedSettings,innerTitle:bindViewModel.resx.AdvancedSettingsTitle,cancelBtnLbl:'Cancel',acceptBtnLbl:'Save',onAcceptCallback:onAdvancedSettingAccept,closeOnAccept:false,onCloseCallback:onAdvancedSettingCancel},html,getAdvancedViewModel,onAfterBind);});}
var getAdvancedViewModel=function(){var registerNewUsers=false;var listsToInsertNewUsers=[];var roleToSynchronize='';for(var i=bindViewModel.configurations.length-1;i>=0;i--){var config=bindViewModel.configurations[i];if(config.name===constants.INSERT_NEW_USERS_IN_LISTS){registerNewUsers=config.value().toLowerCase()==="true";}
else if(config.name===constants.LISTS_TO_INSERT_NEW_USERS)
{var value=config.value();if(value)
{listsToInsertNewUsers=config.value().split(',');}}
else if(config.name===constants.ROLE_TO_SYNCHRONIZE){var value=config.value();if(value){roleToSynchronize=config.value();}}}
advancedViewModel={apiKey:bindViewModel.apiKey,resx:bindViewModel.resx,lists:ko.observableArray([]),registerNewUsers:ko.observable(registerNewUsers),assignedLists:ko.observableArray(listsToInsertNewUsers),listIsAssigned:listIsAssigned,assignList:assignList,unassignList:unassignList,from:ko.observable(),to:ko.observable(),totalLists:ko.observable(),areListsLoaded:ko.observable(false),showSuccessMessage:ko.observable(false),previousPage:previousPage,nextPage:nextPage,loading:ko.observable(false),apiKeyNotSaved:ko.observable(false),noListsSelectedError:ko.observable(false),roles:ko.observableArray([]),roleToSynchronize:roleToSynchronize,selectedRole:ko.observable()}
return advancedViewModel;}
var onAdvancedSettingAccept=function(){saveAdvancedSettings();}
var onAdvancedSettingCancel=function(){}
var onAfterBind=function(){getAdvancedSettingsModel();}
var getAdvancedSettingsModel=function(){advancedViewModel.loading(true);utility.sf.moduleRoot='dnncorp/MailchimpConnector';utility.sf.controller='Services';if(bindViewModel.apiKey()!=null&&bindViewModel.apiKey().trim().length>0){utility.sf.get('GetAdvancedSettingsModel',{apiKey:bindViewModel.apiKey()},function(data){if(data.apiNotSaved){advancedViewModel.loading(false);advancedViewModel.apiKeyNotSaved(true);return;}
advancedViewModel.apiKeyNotSaved(false);advancedViewModel.lists(data.lists);advancedViewModel.from(data.from);advancedViewModel.to(data.to);advancedViewModel.totalLists(data.totalLists);advancedViewModel.areListsLoaded(true);advancedViewModel.loading(false);advancedViewModel.roles(data.roles);advancedViewModel.selectedRole(advancedViewModel.roleToSynchronize);});}}
var getSettingsModel=function(){advancedViewModel.loading(true);utility.sf.moduleRoot='dnncorp/MailchimpConnector';utility.sf.controller='Services';utility.sf.get('GetSettingsModel',{},function(data){advancedViewModel.registerNewUsers(data.insertNewUsersInLists);advancedViewModel.assignedLists(data.listsToRegister);for(var i=bindViewModel.configurations.length-1;i>=0;i--){var config=bindViewModel.configurations[i];if(config.name===constants.INSERT_NEW_USERS_IN_LISTS){config.value(advancedViewModel.registerNewUsers()+'');}
else if(config.name===constants.LISTS_TO_INSERT_NEW_USERS){var joinedLists=advancedViewModel.assignedLists().join();config.value(joinedLists);}}});}
var onSave=function(koObject){for(var i=bindViewModel.configurations.length-1;i>=0;i--){var config=bindViewModel.configurations[i];if(config.name===constants.API_KEY){apiKeyChanged=config.value()!=bindViewModel.apiKey();config.value(bindViewModel.apiKey());}}}
var saveAdvancedSettings=function(){advancedViewModel.showSuccessMessage(false);var registerNewUsers=advancedViewModel.registerNewUsers();var assignedLists=advancedViewModel.assignedLists();var roleToSynchronize=advancedViewModel.selectedRole();if(registerNewUsers&&!assignedLists.length)
{advancedViewModel.noListsSelectedError(true);return;}
for(var i=bindViewModel.configurations.length-1;i>=0;i--){var config=bindViewModel.configurations[i];if(config.name===constants.INSERT_NEW_USERS_IN_LISTS){config.value(registerNewUsers+'');}
else if(config.name===constants.LISTS_TO_INSERT_NEW_USERS){var joinedLists=assignedLists.join();config.value(joinedLists);}
else if(config.name===constants.ROLE_TO_SYNCHRONIZE){config.value(roleToSynchronize);}}
helper.saveConnection(bindViewModel,function(connected,success){callbackSave();advancedViewModel.showSuccessMessage(success);},true);}
var listIsAssigned=function(listId){var assignedLists=advancedViewModel.assignedLists;var result=assignedLists.indexOf(listId)>-1
return result;}
var assignList=function(list){advancedViewModel.noListsSelectedError(false);var listId=list.id;if(!listIsAssigned(listId)){advancedViewModel.assignedLists.push(listId);}}
var unassignList=function(list){var listId=list.id;if(listIsAssigned(listId)){advancedViewModel.assignedLists.remove(listId);}}
var nextPage=function(){var from=advancedViewModel.from();var to=advancedViewModel.to();var totalLists=advancedViewModel.totalLists();if(to==totalLists){return;}
utility.sf.moduleRoot='dnncorp/MailchimpConnector';utility.sf.controller='Services';utility.sf.get('GetAdvancedSettingsModel',{listsOffset:to},function(data){advancedViewModel.lists(data.lists);advancedViewModel.from(data.from);advancedViewModel.to(data.to);advancedViewModel.totalLists(data.totalLists);});}
var previousPage=function(){var from=advancedViewModel.from();if(from<=1){return;}
utility.sf.moduleRoot='dnncorp/MailchimpConnector';utility.sf.controller='Services';utility.sf.get('GetAdvancedSettingsModel',{listsOffset:from-constants.PAGE_SIZE-1},function(data){advancedViewModel.lists(data.lists);advancedViewModel.from(data.from);advancedViewModel.to(data.to);advancedViewModel.totalLists(data.totalLists);});}
var callbackSave=function(){if(apiKeyChanged)
{getSettingsModel();getAdvancedSettingsModel();}}
return{init:init,onSave:onSave,getActionButtons:function(){return[{className:'primarybtn',text:bindViewModel.resx.Save,action:function(conn,e){conn.save(conn,e,callbackSave);}}];}}});