
window.dnn=dnn||{};window.dnn.ui=dnn.ui||{};window.dnn.ui.components=dnn.ui.components||{};window.dnn.ui.components.upload=dnn.ui.components.upload||{};window.dnn.ui.components.upload.createUploadManager=function(){return((function($,ko){"use strict";window.dnn.ui.components.upload.koFolderPicker($,ko);var onImageUploaded,getFiles,config,browserSupportsDragDrop,requestUtils,selectedFilesIndexOf,wrapper,onError;var viewModel={activeTab:ko.observable("upload-file"),draggingOver:ko.observable(false),uploading:ko.observable(false),uploadPercent:ko.observable(0),uploadUrl:ko.observable(),uploadingFromUrl:ko.observable(false),previewAvailable:ko.observable(false),searchInput:ko.observable(null),selectedFiles:ko.observableArray(),currentFolder:ko.observable({key:-1}),storedFiles:ko.observableArray(),multipleFilesAttribute:ko.observable(null),fromUrlTabVisible:ko.observable(true),acceptedFilesAttribute:ko.observable(null),dragAndDropLiteral:ko.observable(""),insertFileLiteral:ko.observable(""),uploadFileTabVisible:ko.observable(true)};viewModel.activateTab=function(d,e){var tab=e.target.attributes.href.nodeValue.substring(1);viewModel.activeTab(tab);};viewModel.dragOver=function(){if(browserSupportsDragDrop()){viewModel.draggingOver(true);}};viewModel.dragLeave=function(){viewModel.draggingOver(false);};viewModel.uploadFromUrl=function(){if(!viewModel.uploadUrl()||!viewModel.previewAvailable)return;viewModel.uploadingFromUrl(true);var data={url:viewModel.uploadUrl()};requestUtils.request(config.moduleName,config.fileUploadControllerName,config.uploadFromUrlMethodName,'POST',data,onImageUploaded,null,function(){viewModel.uploadingFromUrl(false);});};viewModel.previewUrl=ko.computed(function(){viewModel.previewAvailable(true);return viewModel.uploadUrl();}).extend({throttle:500});viewModel.hidePreview=function(){viewModel.previewAvailable(false);};viewModel.searchText=ko.computed(function(){return viewModel.searchInput();}).extend({throttle:500});viewModel.searchText.subscribe(function(){getFiles();});viewModel.itemClick=function(d,e){if(d.type==='folder'){viewModel.currentFolder({key:d.id,value:d.title,path:d.path});getFiles();}else{if(!config.multipleFiles){viewModel.selectedFiles.removeAll();viewModel.selectedFiles.push(d);}else{var existingFileIdIndex=selectedFilesIndexOf(viewModel.selectedFiles(),d.id);if(existingFileIdIndex>=0){viewModel.selectedFiles.splice(existingFileIdIndex,1);}else{viewModel.selectedFiles.push(d);}}}};selectedFilesIndexOf=function(selectedFiles,id){for(var i=0;i<selectedFiles.length;i++){if(selectedFiles[i].id===id){return i;}}
return-1;};viewModel.insertFileClicked=function(){if(viewModel.selectedFiles().length===0){return;}
var files=viewModel.selectedFiles().map(function(file){var fileName=file.fileName?file.fileName.trim():file.title?file.title.trim():"";return{fileId:file.id,path:file.file||file.image,fileName:fileName};});onImageUploaded(JSON.stringify(files),true);};viewModel.selectedFolderChanged=function(folder){viewModel.currentFolder(folder);viewModel.searchInput('');viewModel.selectedFiles.removeAll();getFiles();};viewModel.isFileSelected=function(fileId){return selectedFilesIndexOf(viewModel.selectedFiles(),fileId)>=0;};function supportAjaxUpload(){var xhr=new XMLHttpRequest;return!!(xhr&&('upload'in xhr)&&('onprogress'in xhr.upload));}
browserSupportsDragDrop=function(){return('draggable'in document.createElement('span'));};function initFileUpload(wrapper,destroyPriorToInit){var url=requestUtils.getServiceUrl(config.moduleName,config.fileUploadControllerName)+config.uploadFileMethodName;if(!supportAjaxUpload()){var antiForgeryToken=$('input[name="__RequestVerificationToken"]').val();url+='?__RequestVerificationToken='+antiForgeryToken+'&ModuleId='+config.moduleId+'&TabId='+config.tabId;}
var uploader=wrapper.find("#uploader");if(destroyPriorToInit){uploader.fileupload('destroy');}
uploader.fileupload({url:url,beforeSend:requestUtils.setHeaders,replaceFileInput:false,dropZone:wrapper.find("div.droparea"),pasteZone:null,submit:function(e,d){viewModel.uploading(true);if(!d.formData){d.formData={};}
return true;},done:function(e,d){var result=supportAjaxUpload()?d.result:$("pre",d.result).html();onImageUploaded(result,false);},always:function(){viewModel.uploading(false);viewModel.draggingOver(false);},error:function(e,d,message){if(onError){var r=JSON.parse(e.responseText);message=r.Message;onError(message);}else{requestUtils.showError(e);}},progress:function(e,data){var percent=data.loaded*100/data.total;viewModel.uploadPercent(percent);},add:function(e,data){if(data.originalFiles[0]['size']>config.maxFileSize){$.dnnAlert({title:'An error has occurred',text:config.fileIsTooLargeLiteral});}else{data.submit();}}});if(!browserSupportsDragDrop()){uploader.parent().addClass("not-supported");}}
function setOnImageUploaded(onImageUploadedCallback){onImageUploaded=onImageUploadedCallback;}
function setOnError(onErrorCallback){onError=onErrorCallback;}
getFiles=function(){var params={keyword:viewModel.searchText(),folderId:viewModel.currentFolder().key,loadRecent:viewModel.currentFolder().key===-1,permission:'READ,ADD'};viewModel.storedFiles.removeAll();requestUtils.request(config.fileBrowserModuleName,config.fileBrowserControllerName,config.getFilesMethodName,'GET',params,function(data){viewModel.storedFiles.removeAll();ko.utils.arrayPushAll(viewModel.storedFiles,data);});};function init(configurations){config=configurations;viewModel.multipleFilesAttribute(config.multipleFiles?"multiple":null);viewModel.fromUrlTabVisible(config.fromUrlTabVisible);viewModel.acceptedFilesAttribute(config.acceptedFilesAttribute?config.acceptedFilesAttribute.trim():null);viewModel.dragAndDropLiteral(config.dragAndDropImageLiteral?config.dragAndDropImageLiteral.trim():"");viewModel.insertFileLiteral(config.insertImageLiteral?config.insertImageLiteral.trim():"");viewModel.uploadFileTabVisible(config.uploadFileTabVisible);if(!viewModel.uploadFileTabVisible()&&viewModel.activeTab()==="upload-file"){viewModel.activeTab("stored-location");}
requestUtils=dnn.ui.components.upload.createRequestUtils();requestUtils.init(config.moduleId);var viewModelBinding=$(config.bindingElementSelector);var node=viewModelBinding[0];if(ko.dataFor(node)){ko.cleanNode(node);}
ko.applyBindings(viewModel,node);wrapper=viewModelBinding;initFileUpload(viewModelBinding,false);if(!config.lazyFilesLoad){getFiles();}}
function setMultipleFiles(multipleFiles){config.multipleFiles=multipleFiles;viewModel.multipleFilesAttribute(config.multipleFiles?"multiple":null);}
function setAcceptedFilesAttribute(acceptedFilesAttribute){config.acceptedFilesAttribute=acceptedFilesAttribute;viewModel.acceptedFilesAttribute(config.acceptedFilesAttribute?config.acceptedFilesAttribute.trim():null);}
function setUploadFileMethodName(uploadFileMethodName){if(config.uploadFileMethodName!==uploadFileMethodName){config.uploadFileMethodName=uploadFileMethodName;initFileUpload(wrapper,true);}}
function setGetFilesMethodName(getFilesMethodName){if(config.getFilesMethodName!==getFilesMethodName){config.getFilesMethodName=getFilesMethodName;}
getFiles();}
function clearSelectedFiles(){viewModel.selectedFiles.removeAll();}
function showDocumentsLiterals(show){if(show){if(config.multipleFiles){viewModel.dragAndDropLiteral(config.dragAndDropDocumentsLiteral?config.dragAndDropDocumentsLiteral.trim():"");viewModel.insertFileLiteral(config.insertDocumentsLiteral?config.insertDocumentsLiteral.trim():"");}else{viewModel.dragAndDropLiteral(config.dragAndDropDocumentLiteral?config.dragAndDropDocumentLiteral.trim():"");viewModel.insertFileLiteral(config.insertDocumentLiteral?config.insertDocumentLiteral.trim():"");}}else{if(config.multipleFiles){viewModel.dragAndDropLiteral(config.dragAndDropImagesLiteral?config.dragAndDropImagesLiteral.trim():"");viewModel.insertFileLiteral(config.insertImagesLiteral?config.insertImagesLiteral.trim():"");}else{viewModel.dragAndDropLiteral(config.dragAndDropImageLiteral?config.dragAndDropImageLiteral.trim():"");viewModel.insertFileLiteral(config.insertImageLiteral?config.insertImageLiteral.trim():"");}}}
function setUploadFileTabVisible(visible){config.uploadFileTabVisible=visible;viewModel.uploadFileTabVisible(config.uploadFileTabVisible);if(!viewModel.uploadFileTabVisible()&&viewModel.activeTab()==="upload-file"){viewModel.activeTab("stored-location");}}
return{init:init,setOnImageUploaded:setOnImageUploaded,setMultipleFiles:setMultipleFiles,setAcceptedFilesAttribute:setAcceptedFilesAttribute,setUploadFileMethodName:setUploadFileMethodName,setGetFilesMethodName:setGetFilesMethodName,clearSelectedFiles:clearSelectedFiles,showDocumentsLiterals:showDocumentsLiterals,setOnError:setOnError,setUploadFileTabVisible:setUploadFileTabVisible};})(jQuery||$,ko));}